(function(){"use strict";
var K="menu_website_brief_v1",client=null;
var TYPES=[["restaurant","مطعم","🍽"],["cafe","مقهى","☕"],["clinic","عيادة","✚"],["salon","صالون","✂"],["retail","متجر","🛍"],["company","شركة","🏢"],["realestate","مكتب عقاري","🏠"],["professional","خدمات مهنية","📋"],["hotel","فندق / شقق","🏨"],["gym","نادي رياضي","💪"],["other","أخرى","✦"]];
var STYLES=[["modern","عصري","واضح ومنظّم","#15120f","#a26a42","#f5f1eb"],["luxury","فاخر","هدوء وثقة","#1a1512","#c9a46c","#f7f2ea"],["minimal","بسيط","مساحات نظيفة","#222","#888","#fafafa"],["corporate","مؤسسي","احترافي رسمي","#1e2a3a","#3d6b9a","#f0f3f7"],["warm","ودّي","قريب من العميل","#3d2b1f","#c47a4a","#faf3eb"],["bold","جريء","حضور قوي","#111","#d44a2a","#f5f5f0"],["elegant","أنيق","تفاصيل راقية","#2a2420","#8b7355","#f8f5f0"]];
var STEPS=["نوع النشاط","الهوية","التواصل","اللغة والأسلوب","الخدمات","الصفحات","المراجعة"];
var DEFAULT_PAGES={restaurant:["home","about","menu","popular","gallery","location","contact","order"],cafe:["home","about","menu","gallery","location","contact"],clinic:["home","about","services","team","booking","location","contact"],salon:["home","services","gallery","booking","location","contact"],retail:["home","products","categories","offers","location","contact"],company:["home","about","services","projects","contact"],realestate:["home","listings","about","contact"],professional:["home","about","services","contact"],hotel:["home","rooms","amenities","booking","location","contact"],gym:["home","programs","trainers","membership","contact"],other:["home","about","services","contact"]};
var PAGE_LABELS={home:"الرئيسية",about:"عنّا",menu:"المنيو",popular:"الأكثر طلبًا",gallery:"معرض",location:"الموقع",contact:"تواصل",order:"طلب / حجز",services:"الخدمات",team:"الفريق",booking:"حجز",products:"المنتجات",categories:"الأقسام",offers:"العروض",projects:"المشاريع",listings:"العقارات",rooms:"الغرف",amenities:"المرافق",programs:"البرامج",trainers:"المدربون",membership:"الاشتراكات"};
var S={step:0,business_type:"",name_ar:"",name_en:"",short_desc:"",full_desc:"",phone:"",whatsapp:"",email:"",address:"",city:"",maps_url:"",social:{instagram:"",tiktok:"",snapchat:"",x:"",facebook:""},hours:{open:"09:00",close:"22:00",days:"يومياً"},services:[{name:"",description:"",price:""}],brand:{primary:"#15120f",accent:"#a26a42",notes:""},language:"ar",style_key:"modern",pages:[],special_notes:"",contact_name:"",country_code:"SA",region:"",currency:"SAR",phone_country_code:"+966"};
function $(i){return document.getElementById(i)}
function esc(s){return String(s||"").replace(/[&<>"]/g,function(m){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':'&quot;'}[m]})}
function load(){try{var d=JSON.parse(localStorage.getItem(K)||"null");if(d)Object.assign(S,d)}catch(e){}}
function save(){try{localStorage.setItem(K,JSON.stringify(S))}catch(e){}}
function initClient(){var c=window.MENU_CONFIG;if(!c||typeof supabase==="undefined")return null;try{return supabase.createClient(c.supabaseUrl,c.supabaseAnonKey)}catch(e){return null}}
function applyPages(){S.pages=(DEFAULT_PAGES[S.business_type]||DEFAULT_PAGES.other).slice()}
function renderSteps(){var el=$("wsSteps");if(!el)return;el.innerHTML=STEPS.map(function(t,i){return'<span class="ws-step-pill'+(i===S.step?" active":i<S.step?" done":"")+'">'+(i+1)+". "+t+"</span>"}).join("")}
function renderTypes(){var el=$("wsTypeGrid");if(!el)return;el.innerHTML=TYPES.map(function(t){return'<button type="button" class="ws-type-card'+(S.business_type===t[0]?" selected":"")+'" data-type="'+t[0]+'"><span class="icon">'+t[2]+'</span><span class="label">'+t[1]+"</span></button>"}).join("");el.querySelectorAll("[data-type]").forEach(function(b){b.onclick=function(){S.business_type=b.getAttribute("data-type");applyPages();save();renderTypes()}})}
function renderStyles(){var el=$("wsStyleGrid");if(!el)return;el.innerHTML=STYLES.map(function(s){var g="linear-gradient(135deg,"+s[3]+","+s[4]+" 55%,"+s[5]+")";return'<button type="button" class="ws-style-card'+(S.style_key===s[0]?" selected":"")+'" data-style="'+s[0]+'"><span class="ws-style-swatch" style="background:'+g+'"></span><span class="meta"><strong>'+s[1]+"</strong><span>"+s[2]+"</span></span></button>"}).join("");el.querySelectorAll("[data-style]").forEach(function(b){b.onclick=function(){S.style_key=b.getAttribute("data-style");save();renderStyles()}})}
function renderPages(){var el=$("wsPages");if(!el)return;if(!S.pages.length)applyPages();var all=DEFAULT_PAGES[S.business_type]||DEFAULT_PAGES.other;el.innerHTML=all.map(function(id){var on=S.pages.indexOf(id)>=0;return'<label class="ws-page-check rec"><input type="checkbox" data-page="'+id+'"'+(on?" checked":"")+">"+(PAGE_LABELS[id]||id)+"</label>"}).join("");el.querySelectorAll("[data-page]").forEach(function(inp){inp.onchange=function(){var id=inp.getAttribute("data-page");if(inp.checked){if(S.pages.indexOf(id)<0)S.pages.push(id)}else S.pages=S.pages.filter(function(x){return x!==id});save()}})}
function renderServices(){var el=$("wsSvcList");if(!el)return;if(!S.services.length)S.services=[{name:"",description:"",price:""}];el.innerHTML=S.services.map(function(s,i){return'<div class="ws-svc-row" data-i="'+i+'"><input placeholder="الاسم" value="'+esc(s.name)+'" data-f="name"><input placeholder="وصف" value="'+esc(s.description)+'" data-f="description"><input placeholder="السعر" value="'+esc(s.price)+'" data-f="price"><button type="button" class="rm" data-rm="'+i+'">حذف</button></div>'}).join("");el.querySelectorAll(".ws-svc-row").forEach(function(row){var i=+row.getAttribute("data-i");row.querySelectorAll("input").forEach(function(inp){inp.oninput=function(){S.services[i][inp.getAttribute("data-f")]=inp.value;save()}})});el.querySelectorAll("[data-rm]").forEach(function(b){b.onclick=function(){S.services.splice(+b.getAttribute("data-rm"),1);if(!S.services.length)S.services.push({name:"",description:"",price:""});save();renderServices()}})}
function val(id){var el=$(id);return el?String(el.value||"").trim():""}
function set(id,v){var el=$(id);if(el)el.value=v||""}
function readAll(){S.name_ar=val("wsNameAr");S.name_en=val("wsNameEn");S.short_desc=val("wsShort");S.full_desc=val("wsFull");S.contact_name=val("wsContactName");S.phone=val("wsPhone");S.whatsapp=val("wsWhatsapp");S.email=val("wsEmail");S.address=val("wsAddress");S.city=val("wsCity");S.maps_url=val("wsMaps");S.social.instagram=val("wsIg");S.social.tiktok=val("wsTt");S.social.snapchat=val("wsSnap");S.social.x=val("wsX");S.social.facebook=val("wsFb");S.hours.open=val("wsOpen");S.hours.close=val("wsClose");S.hours.days=val("wsDays");S.brand.primary=val("wsPrimary")||"#15120f";S.brand.accent=val("wsAccent")||"#a26a42";S.brand.notes=val("wsBrandNotes");S.special_notes=val("wsNotes");var cc=val("wsCountry");if(cc){S.country_code=cc;if(window.MENU_MARKETS){var m=MENU_MARKETS.get(cc);S.currency=m.currency;S.phone_country_code=m.dial}}S.region=val("wsRegion")}
function fill(){set("wsNameAr",S.name_ar);set("wsNameEn",S.name_en);set("wsShort",S.short_desc);set("wsFull",S.full_desc);set("wsContactName",S.contact_name);set("wsPhone",S.phone);set("wsWhatsapp",S.whatsapp);set("wsEmail",S.email);set("wsAddress",S.address);set("wsCity",S.city);set("wsMaps",S.maps_url);set("wsIg",S.social.instagram);set("wsTt",S.social.tiktok);set("wsSnap",S.social.snapchat);set("wsX",S.social.x);set("wsFb",S.social.facebook);set("wsOpen",S.hours.open);set("wsClose",S.hours.close);set("wsDays",S.hours.days);set("wsPrimary",S.brand.primary);set("wsAccent",S.brand.accent);set("wsBrandNotes",S.brand.notes);set("wsNotes",S.special_notes);set("wsRegion",S.region);document.querySelectorAll(".ws-lang-opt").forEach(function(b){b.classList.toggle("selected",b.getAttribute("data-lang")===S.language)});if(window.MENU_MARKETS){MENU_MARKETS.fillSelect($("wsCountry"),S.country_code||"SA");applyMarketLabels()}}
function tLabel(id){var t=TYPES.find(function(x){return x[0]===id});return t?t[1]:id}
function sLabel(id){var t=STYLES.find(function(x){return x[0]===id});return t?t[1]:id}
function langLabel(l){return l==="en"?"English":l==="both"?"عربي + English":"العربية"}
function renderReview(){var el=$("wsReview");if(!el)return;var pl=(S.pages||[]).map(function(id){return PAGE_LABELS[id]||id}).join(" · ");var svc=(S.services||[]).filter(function(s){return s.name}).map(function(s){return s.name+(s.price?" ("+s.price+")":"")}).join(" · ")||"—";var mkt=window.MENU_MARKETS?MENU_MARKETS.label(S.country_code||"SA"):(S.country_code||"SA");el.innerHTML="<h3>ملخص طلب الموقع</h3><dl><dt>النشاط</dt><dd>"+esc(tLabel(S.business_type))+"</dd><dt>الاسم</dt><dd>"+esc(S.name_ar)+(S.name_en?" / "+esc(S.name_en):"")+"</dd><dt>الدولة</dt><dd>"+esc(mkt)+"</dd><dt>المنطقة/المدينة</dt><dd>"+esc((S.region?S.region+" · ":"")+(S.city||"—"))+"</dd><dt>الجوال</dt><dd>"+esc(S.phone||S.whatsapp||"—")+"</dd><dt>اللغة</dt><dd>"+esc(langLabel(S.language))+"</dd><dt>الأسلوب</dt><dd>"+esc(sLabel(S.style_key))+"</dd><dt>الصفحات</dt><dd>"+esc(pl||"—")+"</dd><dt>الخدمات</dt><dd>"+esc(svc)+"</dd></dl>"}
function show(){document.querySelectorAll(".ws-panel").forEach(function(p,i){p.classList.toggle("active",i===S.step)});renderSteps();if(S.step===0)renderTypes();if(S.step===1||S.step===2||S.step===3)fill();if(S.step===3)renderStyles();if(S.step===4)renderServices();if(S.step===5)renderPages();if(S.step===6){readAll();renderReview()}var prev=$("wsPrev"),next=$("wsNext"),sub=$("wsSubmit");if(prev)prev.hidden=S.step===0;if(next)next.hidden=S.step===STEPS.length-1;if(sub)sub.hidden=S.step!==STEPS.length-1;var msg=$("wsMsg");if(msg){msg.textContent="";msg.className="ws-msg"}}
function validate(){if(S.step===0&&!S.business_type)return"اختر نوع النشاط للمتابعة.";if(S.step===1){readAll();if(!S.name_ar)return"أدخل اسم النشاط بالعربية."}if(S.step===2){readAll();if(!S.phone&&!S.whatsapp)return"أدخل رقم الجوال أو واتساب."}if(S.step===5&&(!S.pages||!S.pages.length))return"اختر صفحة واحدة على الأقل.";return null}
async function submit(){var msg=$("wsMsg"),btn=$("wsSubmit");var err=validate();if(err){if(msg){msg.textContent=err;msg.className="ws-msg err"}return}if(!client){if(msg){msg.textContent="تعذر الاتصال بالخادم.";msg.className="ws-msg err"}return}readAll();if(btn){btn.disabled=true;btn.textContent="جارٍ الإرسال…"}try{var payload={business_type:S.business_type,name_ar:S.name_ar,name_en:S.name_en||null,short_desc:S.short_desc||null,full_desc:S.full_desc||null,phone:S.phone||null,whatsapp:S.whatsapp||null,email:S.email||null,address:S.address||null,city:S.city||null,maps_url:S.maps_url||null,social:S.social,hours:S.hours,services:(S.services||[]).filter(function(s){return s.name&&s.name.trim()}),brand:S.brand,language:S.language,style_key:S.style_key,pages:S.pages,special_notes:S.special_notes||null,contact_name:S.contact_name||null,contact_phone:S.whatsapp||S.phone||null,country_code:S.country_code||"SA",region:S.region||null,currency:S.currency||"SAR",phone_country_code:S.phone_country_code||null};var r=await client.rpc("submit_website_brief",{p_payload:payload});if(r.error)throw r.error;try{localStorage.removeItem(K)}catch(e){}if(msg){msg.textContent="تم استلام طلبك بنجاح. سيتواصل معك فريق Menu.";msg.className="ws-msg ok"}var board=$("wsStatusBoard");if(board){board.classList.add("show");var id=r.data&&r.data.id?String(r.data.id).slice(0,8):"—";board.innerHTML='<div class="ws-status-card"><span class="ws-status-badge">تم الاستلام</span><h3 style="margin:12px 0 8px">طلب موقع: '+esc(S.name_ar)+'</h3><p style="margin:0;color:var(--muted);font-size:14px">مرجع: <code dir="ltr">'+esc(id)+"</code></p></div>"}if(btn)btn.textContent="تم الإرسال"}catch(e){if(msg){msg.textContent="تعذر الإرسال: "+(e.message||"");msg.className="ws-msg err"}if(btn){btn.disabled=false;btn.textContent="إرسال طلب الموقع"}}}
function bind(){var start=$("wsStart");if(start)start.onclick=function(e){e.preventDefault();var w=$("wsWizard");if(w)w.scrollIntoView({behavior:"smooth",block:"start"})};var prev=$("wsPrev"),next=$("wsNext"),sub=$("wsSubmit");if(prev)prev.onclick=function(){if(S.step>0){S.step--;save();show()}};if(next)next.onclick=function(){var err=validate(),msg=$("wsMsg");if(err){if(msg){msg.textContent=err;msg.className="ws-msg err"}return}readAll();if(S.step<STEPS.length-1){S.step++;save();show()}};if(sub)sub.onclick=submit;document.querySelectorAll(".ws-lang-opt").forEach(function(b){b.onclick=function(){S.language=b.getAttribute("data-lang");save();document.querySelectorAll(".ws-lang-opt").forEach(function(x){x.classList.toggle("selected",x.getAttribute("data-lang")===S.language)})}});var add=$("wsAddSvc");if(add)add.onclick=function(){S.services.push({name:"",description:"",price:""});save();renderServices()}}
function applyMarketLabels(){if(!window.MENU_MARKETS)return;var m=MENU_MARKETS.get(S.country_code||"SA");var rl=$("wsRegionLabel");if(rl)rl.textContent=m.region_label;var ri=$("wsRegion");if(ri)ri.placeholder=m.region_placeholder;var ci=$("wsCity");if(ci)ci.placeholder=m.city_placeholder;var dh=$("wsDialHint");if(dh)dh.textContent=m.dial;S.currency=m.currency;S.phone_country_code=m.dial}function initMarketWs(){if(!window.MENU_MARKETS)return;MENU_MARKETS.fillSelect($("wsCountry"),S.country_code||"SA");applyMarketLabels();var sel=$("wsCountry");if(sel)sel.onchange=function(){S.country_code=sel.value||"SA";applyMarketLabels();save()}}function boot(){client=initClient();load();initMarketWs();bind();show()}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot);else boot();
})();
